SELECT DISTINCT 
TGFCAB.NUNOTA, 
TGFCAB.NUMNOTA, 
TGFCAB.DTNEG, 
TGFCAB.DTFATUR, 
TGFCAB.CODPARC,
TGFPAR.NOMEPARC,
TGFCAB.CODTIPOPER,
TGFTOP.DESCROPER,
TGFCAB.TIPMOV,
TGFCAB.CODTIPVENDA,
TGFCAB.OBSERVACAO,
TGFCAB.VLRNOTA,
TGFCAB.LIBCONF,
TGFCAB.NUCONFATUAL,
TGFCON2.*
FROM TGFCAB
LEFT JOIN TGFCON2 ON TGFCON2.NUCONF = TGFCAB.NUCONFATUAL
LEFT JOIN TGFPAR ON TGFCAB.CODPARC = TGFPAR.CODPARC
LEFT JOIN TGFTOP ON TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
WHERE TGFCAB.STATUSNOTA != 'L'
AND TGFCAB.LIBCONF = 'S'