SELECT DISTINCT
  TAB.CODPRODMP,
  TAB.DESCRPROD,
  TAB.CODVOL,
  TAB.CODGRUPOPROD AS CODGRUPOPRODMP,
  TAB.DESCRGRUPOPROD AS DESCRGRUPOPRODMP,
  TAB.CODPRODPA,
  PRO2.DESCRPROD AS DESCRPA,
  PRO2.CODGRUPOPROD,
  GRU2.DESCRGRUPOPROD,
  PRC.VERSAO,
  TAB.QTDMISTURA,
  (TAB.QTDMISTURA * :QTD_MULTP) AS QTD_SIMULADA,
  TAB.DHCAD,
  NVL(F_DESCROPC('TGFPRO', 'USOPROD', TAB.USOPROD),'Serviço') AS USOPROD,
  F_DESCROPC('TPRLMP', 'TIPOUSOMP', TAB.TIPOUSOMP) AS TIPOUSOMP
FROM TPRIPROC OPE
INNER JOIN TPRPRC PRC ON PRC.IDPROC = OPE.IDPROC
INNER JOIN TPRIPA IPA ON IPA.IDIPROC = OPE.IDIPROC
INNER JOIN TGFPRO PRO2 ON CODPRODPA = PRO2.CODPROD
INNER JOIN TGFGRU GRU2 ON PRO2.CODGRUPOPROD = GRU2.CODGRUPOPROD
INNER JOIN (
    SELECT
      EFX.IDPROC,
      LMP.CODPRODPA,
      LMP.CONTROLEPA,
      LMP.CONTROLEMP,
      LMP.CODPRODMP,
      PRO.DESCRPROD,
      GRU.CODGRUPOPROD,
      GRU.DESCRGRUPOPROD,
      PRO.USOPROD,
      LMP.TIPOUSOMP,
      LMP.TIPOQTD,
      LMP.QTDMISTURA,
      LMP.CODVOL,
      LMP.GERAREQUISICAO,
      LMP.CODLOCALORIG,
      LMP.DHCAD,
      LOC.DESCRLOCAL,
      PRO.DECQTD,
      PRO.REFERENCIA
    FROM TPRLMP LMP
    JOIN TGFPRO PRO ON PRO.CODPROD = LMP.CODPRODMP
    JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD 
    JOIN TPREFX EFX ON EFX.IDEFX = LMP.IDEFX
    JOIN TGFLOC LOC ON LOC.CODLOCAL = LMP.CODLOCALORIG
) TAB ON TAB.IDPROC = PRC.IDPROC AND TAB.CODPRODPA = IPA.CODPRODPA AND (TAB.CONTROLEPA IS NULL OR TAB.CONTROLEPA = IPA.CONTROLEPA)
WHERE OPE.STATUSPROC IN ('A','R','F')
  AND TAB.USOPROD <> 'S'
  AND TAB.TIPOUSOMP <> 'R'
  AND (TAB.CODPRODMP = :COD_MP OR :COD_MP IS NULL)
  AND (PRO2.CODGRUPOPROD = ANY :GRUPO_PA)
  AND (TAB.CODPRODPA = ANY :CODS_PA)
  AND (:DESC_PA IS NULL OR UPPER(PRO2.DESCRPROD) LIKE '%' || UPPER(:DESC_PA) || '%')
  AND (:DESC_MP IS NULL OR UPPER(TAB.DESCRPROD) LIKE '%' || UPPER(:DESC_MP) || '%')
  AND (
      (:VERSAO_OP = 1) -- Quando 1, mostra todas as versões
      OR
      (:VERSAO_OP = 2 AND PRC.VERSAO = (
          SELECT MAX(PRC2.VERSAO)
          FROM TPRPRC PRC2
          INNER JOIN TPRIPROC OPE2 ON OPE2.IDPROC = PRC2.IDPROC
          INNER JOIN TPRIPA IPA2 ON IPA2.IDIPROC = OPE2.IDIPROC
          WHERE OPE2.STATUSPROC IN ('A','R','F')
          AND IPA2.CODPRODPA = TAB.CODPRODPA
          AND (TAB.CONTROLEPA IS NULL OR IPA2.CONTROLEPA = TAB.CONTROLEPA)
      )) -- Quando 2, mostra apenas a maior versão
  )
GROUP BY TAB.CODPRODMP, TAB.DESCRPROD, TAB.CODVOL, TAB.USOPROD, TAB.TIPOUSOMP, TAB.CODPRODPA, PRC.VERSAO, TAB.QTDMISTURA,PRO2.DESCRPROD,PRO2.CODGRUPOPROD,GRU2.DESCRGRUPOPROD,TAB.DHCAD,TAB.CODGRUPOPROD,TAB.DESCRGRUPOPROD
ORDER BY TAB.CODPRODPA, TAB.CODPRODMP