SELECT
    TSIRLG.CODUSU,
    TSIUSU.NOMEUSU,
    TSIUSU.CODGRUPO,
    TSIGRU.NOMEGRUPO,
    TSIRLG.SEQACESSO,
    TSIRLG.LOGIN,
    TSIRLG.LOGOUT,
    (TSIRLG.LOGOUT - TSIRLG.LOGIN)*24 AS TEMP_ACESSO,
    TSIRLG.IP,
    TSIACM.CAMINHO,
    TSIACM.DESCRMENU
FROM
    TSIRLG
    INNER JOIN TSIACM
    ON TSIRLG.SEQACESSO = TSIACM.SEQACESSO
    INNER JOIN TSIUSU
    ON TSIRLG.CODUSU = TSIUSU.CODUSU
    INNER JOIN TSIGRU
    ON TSIUSU.CODGRUPO = TSIGRU.CODGRUPO
WHERE
    TSIRLG.CODUSU <> 0