SELECT TGFCAB.NUNOTA, 
TGFCAB.NUMNOTA, 
TGFCAB.DTNEG, 
TGFCAB.DTFATUR, 
TGFCAB.CODPARC,
TGFCAB.CODTIPOPER, 
TGFCAB.TIPMOV,
TGFCAB.CODTIPVENDA,
TGFCAB.OBSERVACAO,
TGFCAB.VLRNOTA,
TGFCAB.LIBCONF,
TGFCAB.NUCONFATUAL,
TGFCON2.*
FROM TGFCAB
LEFT JOIN TGFCON2 ON TGFCON2.NUCONF = TGFCAB.NUCONFATUAL
WHERE TGFCAB.STATUSNOTA != 'L'
AND TGFCAB.LIBCONF = 'S'