--Pedidos Pendentes
WITH PEDIDOS AS (
  SELECT
    DISTINCT TGFCAB.DTNEG,
    TGFCAB.DTPREVENT,
    TGFCAB.CODPARC,
    TGFPAR.NOMEPARC,
    TGFPAR.RAZAOSOCIAL,
    TGFCAB.NUNOTA,
    TGFCAB.NUMNOTA,
    TGFCAB.VLRNOTA,
    (
      SELECT
        SUM(TGFITE.VLRUNIT * TGFITE.QTDENTREGUE)
      FROM
        TGFITE
      WHERE
        TGFITE.NUNOTA = TGFCAB.NUNOTA
    ) AS VLR_TOTAL_ENTREGUE,
    TGFCAB.CODTIPOPER,
    TGFTOP.DESCROPER,
    TGFCAB.CODTIPVENDA,
    TGFTPV.DESCRTIPVENDA,
    TGFCAB.CODVEND,
    TGFVEN.APELIDO,
    TGFCAB.STATUSNOTA,
    VSILIB.DHLIB,
    TO_CHAR(TRUNC(SYSDATE - TGFCAB.DTNEG)) AS DIAS_EM_ABERTO,
    TGFCAB.TIPMOV,
    TGFCAB.CODUSUINC,
    TSIUSU.NOMEUSU,
    TGFCAB.PENDENTE,
    TGFCAB.AD_NPROPOSTA,
    (
      SELECT
        COUNT(
          CASE
            WHEN TGFITE.PENDENTE = 'S' THEN
              1
          END)
      FROM
        TGFITE
      WHERE
        TGFITE.NUNOTA = TGFCAB.NUNOTA
    ) AS TOTAL_PENDENTE,
    (
      SELECT
        COUNT(
          CASE
            WHEN TGFITE.PENDENTE = 'N' THEN
              1
          END)
      FROM
        TGFITE
      WHERE
        TGFITE.NUNOTA = TGFCAB.NUNOTA
    ) AS TOTAL_ENTREGUE,
    (
      SELECT
        CASE
          WHEN SUM(TGFITE.QTDNEG - TGFITE.QTDENTREGUE) = 0 THEN
            'Entregue'
          WHEN SUM(TGFITE.QTDNEG - TGFITE.QTDENTREGUE) > 0 AND SUM(TGFITE.QTDNEG - TGFITE.QTDENTREGUE) < SUM(TGFITE.QTDNEG) THEN
            'Parcial'
          WHEN SUM(TGFITE.QTDNEG - TGFITE.QTDENTREGUE) = SUM(TGFITE.QTDNEG) THEN
            'Pendente'
        END
      FROM
        TGFITE
      WHERE
        TGFITE.NUNOTA = TGFCAB.NUNOTA
    ) AS STATUS_TOTAL
  FROM
    TGFCAB
    INNER JOIN TGFPAR
    ON TGFCAB.CODPARC = TGFPAR.CODPARC
    INNER JOIN TGFTOP
    ON TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
    INNER JOIN TGFTPV
    ON TGFCAB.CODTIPVENDA = TGFTPV.CODTIPVENDA
    INNER JOIN TGFVEN
    ON TGFCAB.CODVEND = TGFVEN.CODVEND
    INNER JOIN TSIUSU
    ON TGFCAB.CODUSUINC = TSIUSU.CODUSU
    INNER JOIN VSILIB
    ON TGFCAB.NUNOTA = VSILIB.NUNOTA
  WHERE
    TGFCAB.STATUSNOTA = 'L'
    AND TGFCAB.TIPMOV = 'O'
    AND TGFCAB.CODTIPOPER <> '1316'
    AND TGFCAB.CODTIPOPER <> '1964'
)
SELECT
  *
FROM
  PEDIDOS
WHERE
  (CODPARC = :P_PARC
  OR :P_PARC IS NULL)
  AND (CODVEND = :P_COMPRADOR
  OR :P_COMPRADOR IS NULL)
  AND (DTNEG >= :P_DTINICIO
  OR :P_DTINICIO IS NULL)
  AND (DTNEG <= :P_DTFIM
  OR :P_DTFIM IS NULL)
  AND (STATUS_TOTAL IN (:P_STATUS)
  OR :P_STATUS IS NULL)