--Itens Pendentes de Pedidos
SELECT
        DISTINCT 
        PAR.NOMEPARC,
        PAR.CODPARC, -- Qualificado com PAR
        ITE.CODPROD,
        COALESCE(DTP.DTPREV, ITE.DTINICIO) AS DTPREV,
        CAB.DTPREVENT,
        CAB.NUNOTA AS CAB_NUNOTA, -- Qualificado com CAB
        PRO.DESCRPROD,
        ITE.SEQUENCIA AS ITE_SEQUENCIA, -- Qualificado com ITE
        ITE.QTDNEG,
        CAB.DTNEG AS CAB_DTNEG, -- Qualificado com CAB
        TO_CHAR(TRUNC(SYSDATE - CAB.DTNEG)) AS DIAS_EM_ABERTO, -- Parêntese corrigido
        PRO.CODVOL,
        ITE.QTDENTREGUE,
        CASE
            WHEN (ITE.QTDNEG - ITE.QTDENTREGUE) = 0 THEN 'Entregue'
            WHEN ITE.QTDENTREGUE = 0 THEN 'Pendente'
            WHEN ITE.QTDENTREGUE > 0 THEN 'Parcial'
        END AS status_total,
        (ITE.QTDNEG - ITE.QTDENTREGUE) AS QTDPENDENTE,
        ITE.VLRUNIT,
        ITE.VLRTOT,
        ITE.CONTROLE,
        ITE.PENDENTE,
        PRO.NCM,
        CAB.CODTIPOPER,
        TOP.DESCROPER,
        CAB.CODTIPVENDA,
        VEN.CODVEND,
        VEN.APELIDO,
        TPV.DESCRTIPVENDA,
        CAB.AD_NPROPOSTA,
        -- NUNOTA relacionado da TGFVAR
        CAB2.NUMNOTA AS NUNOTA_RELACIONADO,
        -- QTDNEG da TGFITE relacionada ao CAB2.NUNOTA
        ITE2.QTDNEG AS QTDNEG_RELACIONADA
    FROM
        TGFITE ITE
        INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
        INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
        INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
        INNER JOIN TGFTPV TPV ON CAB.CODTIPVENDA = TPV.CODTIPVENDA
        INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
        INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
        LEFT JOIN TGFDTP DTP ON (ITE.NUNOTA = DTP.NUNOTA AND DTP.SEQUENCIA = ITE.SEQUENCIA)
        -- LEFT JOIN para trazer o NUNOTA relacionado da TGFVAR
        LEFT JOIN TGFVAR VAR ON VAR.NUNOTAORIG = ITE.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA
        LEFT JOIN TGFCAB CAB2 ON VAR.NUNOTA = CAB2.NUNOTA
        -- LEFT JOIN para trazer a QTDNEG da TGFITE relacionada ao CAB2.NUNOTA
        LEFT JOIN TGFITE ITE2 ON CAB2.NUNOTA = ITE2.NUNOTA AND VAR.SEQUENCIA = ITE2.SEQUENCIA
    WHERE
        CAB.STATUSNOTA = 'L'
        AND CAB.TIPMOV = 'O'
        AND CAB.CODTIPOPER <> '1316'
        AND CAB.CODTIPOPER <> '1964'
        AND (PAR.CODPARC = :P_PARC OR :P_PARC IS NULL) -- Qualificado com PAR
        AND (VEN.CODVEND = :P_COMPRADOR OR :P_COMPRADOR IS NULL) -- Qualificado com VEN
        AND (CAB.DTNEG >= :P_DTINICIO OR :P_DTINICIO IS NULL) -- Qualificado com CAB
        AND (CAB.DTNEG <= :P_DTFIM OR :P_DTFIM IS NULL) -- Qualificado com CAB

        '#00FF66'