-- Itens de Pedidos Pendentes com Subconsulta
SELECT 
    PAR.NOMEPARC,
    ITE.CODPROD,
    CAB.NUNOTA,
    PRO.DESCRPROD,
    ITE.NUNOTA,
    ITE.SEQUENCIA,
    ITE.QTDNEG,
    PRO.CODVOL,
    ITE.QTDENTREGUE,
    (ITE.QTDNEG - ITE.QTDENTREGUE) AS QTDPENDENTE,
    ITE.VLRUNIT,
    ITE.VLRTOT,
    ITE.CONTROLE,
    ITE.PENDENTE,
    PRO.NCM,
    CAB.AD_NPROPOSTA,
    TO_CHAR(TRUNC(SYSDATE - CAB.DTNEG)) AS DIAS_EM_ABERTO,

    -- Subconsulta para buscar o NUNOTA relacionado em TGFVAR
    (SELECT CAB2.NUMNOTA
     FROM TGFVAR VAR
     INNER JOIN TGFCAB CAB2 ON VAR.NUNOTA = CAB2.NUNOTA
     WHERE VAR.NUNOTAORIG = ITE.NUNOTA
       AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA
     FETCH FIRST 1 ROWS ONLY) AS NUNOTA_RELACIONADO
FROM
    TGFITE ITE
    INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
    INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
    INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE
    CAB.STATUSNOTA = 'L'
    AND CAB.TIPMOV = 'O'
    AND ITE.NUNOTA = :A_NUNOTA
ORDER BY
    CAB.NUNOTA, ITE.SEQUENCIA