SELECT DISTINCT
    TPRIPROC.IDIPROC,
    TPRIPROC.DHINC,
    TPRIPROC.DHTERMINO,
    CASE
        WHEN TPRIPROC.STATUSPROC = 'R' THEN '<span style="font-weight:bold; background-color:#FFFF66;">Criada</span>'
        WHEN TPRIPROC.STATUSPROC = 'A' THEN '<span style="font-weight:bold; background-color:#83E28E;">Em andamento</span>'
        WHEN TPRIPROC.STATUSPROC = 'F' THEN '<span style="font-weight:bold;">Finalizada</span>'
    END AS STATUS_OP,
    TPRIPA.CODPRODPA,
    TPRLMP.CODPRODMP,
    TGFPRO.DESCRPROD,
    TPRLMP.QTDMISTURA,
    (TPRIPA.QTDPRODUZIR * TPRLMP.QTDMISTURA) AS QTDNECLOTE,
    COALESCE(TOTAIS.TOTALEMP, 0) AS TOTALEMP,
    TOTAIS.CONTROLE,
 (SELECT SUM(EST.ESTOQUE)
     FROM TGFEST EST
     WHERE EST.CODPROD = TPRLMP.CODPRODMP
       AND EST.CODLOCAL = '1010000') AS TOTAL_LOCAL_1010000,
    -- Total de estoque para o local 1020000
    (SELECT SUM(EST.ESTOQUE)
     FROM TGFEST EST
     WHERE EST.CODPROD = TPRLMP.CODPRODMP
       AND EST.CODLOCAL = '1020000') AS TOTAL_LOCAL_1020000
FROM TPRLMP
    INNER JOIN TPRATV ON TPRLMP.IDEFX = TPRATV.IDEFX
    INNER JOIN TPRLPA ON TPRATV.IDPROC = TPRLPA.IDPROC
    INNER JOIN TPRIPROC ON TPRLPA.IDPROC = TPRIPROC.IDPROC
    INNER JOIN TPRIPA ON TPRIPROC.IDIPROC = TPRIPA.IDIPROC
    INNER JOIN TGFPRO ON TPRLMP.CODPRODMP = TGFPRO.CODPROD
    LEFT JOIN (
        SELECT
            TGFITE.CODPROD,
            TGFCAB.IDIPROC,
            TGFITE.CONTROLE,
            SUM(TGFITE.QTDNEG) AS TOTALEMP
        FROM TGFITE
        INNER JOIN TGFCAB ON TGFITE.NUNOTA = TGFCAB.NUNOTA
        WHERE TGFITE.SEQUENCIA > 0
        AND TGFCAB.STATUSNOTA = 'L'
        AND TGFCAB.CODTIPOPER = ANY ('1951','1950')
        GROUP BY TGFITE.CODPROD, TGFCAB.IDIPROC, TGFITE.CONTROLE
    ) TOTAIS ON TPRIPROC.IDIPROC = TOTAIS.IDIPROC
            AND TPRLMP.CODPRODMP = TOTAIS.CODPROD
WHERE
   (TPRIPROC.DHINC >= :dt_inicio)
    AND (TPRIPROC.DHINC <= :dt_fim OR :dt_fim is null)
    AND (TPRIPROC.IDIPROC = ANY (:n_op) OR :n_op IS NULL)
    AND (TPRIPA.CODPRODPA = ANY (:cod_pa) OR :cod_pa IS NULL)
    AND (TPRLMP.CODPRODMP = ANY (:cod_mp) OR :cod_mp IS NULL)
    AND (TPRIPA.CODPRODPA = TPRLMP.CODPRODPA)
    AND (CASE
        WHEN TPRIPROC.STATUSPROC = 'R' THEN 'Criada'
        WHEN TPRIPROC.STATUSPROC = 'A' THEN 'Em andamento'
        WHEN TPRIPROC.STATUSPROC = 'F' THEN 'Finalizada'
    END) IN ('Criada', 'Em andamento', 'Finalizada')