SELECT DISTINCT
TGFCAB.IDIPROC,
TGFCAB.NUNOTA,
TGFCAB.DTNEG,
CASE
    WHEN TGFCAB.STATUSNOTA = 'L' THEN '<span style="font-weight:bold; background-color:#83E28E;">Confirmada</span>'
    ELSE '<span style="font-weight:bold; background-color:#FFFF66;">Não Confirmada</span>'
END AS STATUS_nota,
TPRIPA.CODPRODPA,
TGFPRO.DESCRPROD,
TGFITE.CODPROD,
TGFITE.QTDNEG
FROM TGFITE
INNER JOIN TGFCAB ON TGFITE.NUNOTA = TGFCAB.NUNOTA
INNER JOIN TPRIPROC ON TPRIPROC.IDIPROC = TGFCAB.IDIPROC
INNER JOIN TPRIPA ON TPRIPA.IDIPROC = TPRIPROC.IDIPROC
INNER JOIN TGFPRO ON TGFPRO.CODPROD = TPRIPA.CODPRODPA
WHERE TGFCAB.IDIPROC = :A_IDIPROC
AND TGFITE.CODPROD = :A_CODPROD
AND TGFCAB.CODTIPOPER = ANY ('1951','1950')