SELECT
    DISTINCT TGFCAB.DTNEG,
    TGFCAB.DTFATUR,
    TGFITE.CODPROD,
    TGFPRO.DESCRPROD,
    COALESCE(TGFITE.QTDNEG * TGFVOA.QUANTIDADE, TGFITE.QTDNEG)   AS QTDCONVERCAO,
    TGFITE.CODVOL                                                AS UNIDADE_NOTA,
    COALESCE(TGFITE.VLRUNIT / TGFVOA.QUANTIDADE, TGFITE.VLRUNIT) AS VLRCONVERCAO,
    TGFITE.QTDNEG,
    TGFPRO.CODVOL                                                AS UNIDADE_PADRAO,
    TGFITE.VLRUNIT,
    TGFCUSITE.ENTRADASEMICMS,
    TGFITE.VLRTOT,
    (TGFITE.QTDNEG*TGFCUSITE.ENTRADASEMICMS)                     AS VLR_TOT_SEM_IMP,
    TGFCAB.CODPARC,
    TGFPAR.NOMEPARC,
    TGFCAB.NUMNOTA,
    TGFITE.NUNOTA,
    TGFCAB.CODTIPVENDA,
    TGFTPV.DESCRTIPVENDA,
    TGFPAR.RAZAOSOCIAL,
    TGFITE.STATUSNOTA,
    TGFITE.SEQUENCIA,
    TGFITE.BASEICMS,
    TGFITE.ALIQICMS,
    TGFITE.VLRICMS,
    TGFITE.BASEIPI,
    TGFITE.ALIQIPI,
    TGFITE.VLRIPI,
    TGFCAB.CODTIPOPER,
    TGFTOP.DESCROPER
FROM
    TGFITE
    INNER JOIN TGFCAB
    ON TGFITE.NUNOTA = TGFCAB.NUNOTA
    INNER JOIN TGFPAR
    ON TGFCAB.CODPARC = TGFPAR.CODPARC
    INNER JOIN TGFCUSITE
    ON TGFITE.NUNOTA = TGFCUSITE.NUNOTA
    AND TGFITE.SEQUENCIA = TGFCUSITE.SEQUENCIA
    INNER JOIN TGFTOP
    ON TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
    INNER JOIN TGFTPV
    ON TGFCAB.CODTIPVENDA = TGFTPV.CODTIPVENDA
    INNER JOIN TGFPRO
    ON TGFITE.CODPROD = TGFPRO.CODPROD
    LEFT JOIN TGFVOA
    ON TGFVOA.CODPROD = TGFITE.CODPROD
    AND TGFVOA.CODVOL = TGFITE.CODVOL
WHERE
    TGFCAB.TIPMOV = 'C'
    AND TRUNC(TGFCAB.DTNEG) >= :P_DTENTRADA
    OR :P_DTENTRADA IS NULL
    AND TRUNC(TGFCAB.DTNEG) <= :P_DTENTRADA2
    OR :P_DTENTRADA2 IS NULL
    AND TGFCAB.CODPARC <> '2'
    AND TGFCAB.CODPARC <> '101'
    AND TGFCAB.CODTIPOPER <> '1452'
    AND TGFCAB.CODTIPOPER <> '1951'
    AND TGFCAB.CODTIPOPER <> '1900'
    AND (TGFITE.CODPROD = :P_CODPROD
    OR :P_CODPROD IS NULL)
    AND (TGFCAB.CODPARC = :P_CODPARC
    OR :P_CODPARC IS NULL)
    AND (TGFCAB.NUNOTA = :P_NUNOTA
    OR :P_NUNOTA IS NULL)