SELECT
    TGFITE.NUNOTA,
    TGFITE.CODPROD,
    COALESCE(TGFITE.QTDNEG * TGFVOA.QUANTIDADE, TGFITE.QTDNEG) AS QTDCONVERCAO,--
    TGFITE.CODVOL,
    COALESCE(TGFITE.VLRUNIT / TGFVOA.QUANTIDADE, TGFITE.VLRUNIT) AS VLRCONVERCAO,
    TGFITE.QTDNEG,
    TGFPRO.CODVOL,
    TGFITE.VLRUNIT

FROM
    TGFITE
    INNER JOIN TGFPRO
    ON TGFPRO.CODPROD = TGFITE.CODPROD
    LEFT JOIN TGFVOA
    ON TGFVOA.CODPROD = TGFITE.CODPROD
    AND TGFVOA.CODVOL = TGFITE.CODVOL
