SELECT
    TGFFIN.RECDESP,
    TGFFIN.CODNAT,
    TGFNAT.DESCRNAT,
    TGFFIN.CODPARC,
    TGFPAR.NOMEPARC,
    TGFFIN.DHBAIXA,
    TGFFIN.VLRDESDOB
FROM
    TGFFIN
    INNER JOIN TGFNAT
    ON TGFFIN.CODNAT = TGFNAT.CODNAT
    INNER JOIN TGFPAR
    ON TGFFIN.CODPARC = TGFPAR.CODPARC
WHERE
    TGFFIN.PROVISAO = 'N'
    AND TGFFIN.DHBAIXA IS NOT NULL