SELECT DISTINCT
    TGFITE.NUNOTA,
    CAB.AD_NPROPOSTA,
    TGFITE.CODPROD,
    TPRIPA.IDIPROC,
    TPRIPROC.NUNOTA AS PEDIDO_VENDA,
    TGFPRO1.DESCRPROD AS DESCRPROD_ITEM,
    TGFITE.QTDNEG,
    TGFCAB.IDIPROC,
    TPRIPA.CODPRODPA,
    TGFPRO2.DESCRPROD,
    SUBSTRING(TGFPRO2.DESCRPROD, 1, 6) AS DESCRPROD_PA,
    TGFITE.CONTROLE,
    TGFITE.CODLOCALORIG,
    TGFITE.VLRTOT,
    TGFCUSITE.ENTRADASEMICMS AS VALOR_SEM_ICMS,
    TGFCUSITE.ENTRADACOMICMS AS VALOR_COM_ICMS,
    (TGFCUSITE.ENTRADASEMICMS * TGFITE.QTDNEG) AS TOTAL_SEM_ICMS,
    (TGFCUSITE.ENTRADACOMICMS * TGFITE.QTDNEG) AS TOTAL_COM_ICMS,    
    TGFCAB.DTNEG
FROM TGFITE
INNER JOIN TGFCAB ON TGFITE.NUNOTA = TGFCAB.NUNOTA
INNER JOIN TPRIPA ON TGFCAB.IDIPROC = TPRIPA.IDIPROC
INNER JOIN TGFPRO TGFPRO1 ON TGFITE.CODPROD = TGFPRO1.CODPROD
INNER JOIN TGFPRO TGFPRO2 ON TPRIPA.CODPRODPA = TGFPRO2.CODPROD
INNER JOIN TPRIPROC ON TPRIPA.IDIPROC = TPRIPROC.IDIPROC
LEFT JOIN TGFCAB CAB ON TPRIPROC.NUNOTA = CAB.NUNOTA
LEFT JOIN (
    SELECT 
        CODPROD, CONTROLE, ENTRADASEMICMS, ENTRADACOMICMS,
        ROW_NUMBER() OVER (PARTITION BY CODPROD, CONTROLE ORDER BY DTATUAL DESC) AS RN
    FROM TGFCUSITE
    WHERE SEQUENCIA > 0
) TGFCUSITE ON TGFPRO1.CODPROD = TGFCUSITE.CODPROD 
           AND TGFITE.CONTROLE = TGFCUSITE.CONTROLE
           AND TGFCUSITE.RN = 1
WHERE TGFCAB.TIPMOV = 'F'
AND TGFITE.CODPROD <> TPRIPA.CODPRODPA
AND TGFCAB.DTNEG >= :DT_INIC
AND TGFCAB.DTNEG <= :DT_FIM