SELECT
    TPRIPROC.IDIPROC, 
    F_DESCROPC('TPRIPROC', 'STATUSPROC', TPRIPROC.STATUSPROC) AS STATUSPROC, 
    TPRIPROC.DHINC, 
    TPRIPROC.CODUSUINC || ' - ' || TSIUSU.NOMEUSU AS USUARIOINC, 
    TPRIPROC.PRIORIDADE, 
    TPRIPROC.NUMPS,
    TPRIPROC.NUNOTA,
    TPRIPA.CODPRODPA,
    TGFPRO.DESCRPROD AS DESCRPRODPA,
    TPRIPA.QTDPRODUZIR,
    TGFPRO.CODVOL AS CODVOLPA,
    TGFCAB.AD_NPROPOSTA,
    TGFCAB.NUNOTA AS PED_VENDA
FROM 
TPRIPROC
INNER JOIN TPRIPA ON TPRIPROC.IDIPROC = TPRIPA.IDIPROC
INNER JOIN TGFPRO ON TPRIPA.CODPRODPA = TGFPRO.CODPROD
INNER JOIN TGFCAB ON TPRIPROC.NUNOTA = TGFCAB.NUNOTA
INNER JOIN TSIUSU ON TPRIPROC.CODUSUINC = TSIUSU.CODUSU
WHERE 
    TPRIPROC.STATUSPROC IN ('A','R','P','P2')