SELECT DISTINCT
    TGFCAB.NUNOTA,
    TGFCAB.NUMNOTA,
    TGFCAB.AD_NPROPOSTA,
    TGFCAB.DTPREVENT,
    TGFCAB.DTNEG,
    CASE 
        WHEN TGFITE.PENDENTE = 'S' THEN TO_CHAR(TRUNC(SYSDATE - TGFCAB.DTNEG))
        WHEN TGFITE.PENDENTE = 'N' THEN 'Atendido' 
    END AS DIAS_EM_ABERTO,
    TGFCAB.CODTIPOPER,
    TGFTOP.DESCROPER,    
    TGFITE.CODPROD,
    TGFPRO.DESCRPROD,
    CASE
        WHEN TGFPRO.USOPROD = '1' THEN 'Subproduto'
        WHEN TGFPRO.USOPROD = '2' THEN 'Produto Intermediário'
        WHEN TGFPRO.USOPROD = '4' THEN 'Demonstração'
        WHEN TGFPRO.USOPROD = 'B' THEN 'Brinde'
        WHEN TGFPRO.USOPROD = 'C' THEN 'Consumo'
        WHEN TGFPRO.USOPROD = 'D' THEN 'Revenda (por fórmula)'
        WHEN TGFPRO.USOPROD = 'E' THEN 'Embalagem'
        WHEN TGFPRO.USOPROD = 'F' THEN 'Brinde (NF)'
        WHEN TGFPRO.USOPROD = 'I' THEN 'Imobilizado'
        WHEN TGFPRO.USOPROD = 'M' THEN 'Matéria prima'
        WHEN TGFPRO.USOPROD = 'O' THEN 'Outros insumos'
        WHEN TGFPRO.USOPROD = 'P' THEN 'Em Processo'
        WHEN TGFPRO.USOPROD = 'R' THEN 'Revenda'
        WHEN TGFPRO.USOPROD = 'T' THEN 'Terceiros'
        WHEN TGFPRO.USOPROD = 'V' THEN 'Venda (fabricação própria)'
        ELSE 'Serviço'
    END AS USOPRODUTO,
    TGFITE.QTDNEG,
    TGFPRO.CODVOL,
    TGFITE.SEQUENCIA,
    CASE
        WHEN TGFITE.PENDENTE = 'N' THEN 'Não Pendente'
        WHEN TGFITE.PENDENTE = 'S' THEN 'Pendente'
    END AS PENDENTE,
    CASE
        WHEN (TGFITE.QTDNEG - TGFITE.QTDENTREGUE) <= 0 THEN 0 
        ELSE (TGFITE.QTDNEG - TGFITE.QTDENTREGUE)
    END AS QTDPENDENTE,
    --TGFEST.ESTOQUE AS ESTOQUE_TOTAL,
    --TGFEST.RESERVADO AS ESTOQUE_RESERV,
    --(TGFEST.ESTOQUE - TGFEST.RESERVADO) AS ESTOQUE_DISP,
    TGFVAR.NUNOTA AS NOTA_DESTINO,
    TGFVAR.SEQUENCIA AS SEQUENCIA_DESTINO,
    DestinoItem.QTDNEG AS QTD_NEG_DESTINO,
    DestinoItem.QTDENTREGUE AS QTD_ENTREGUE_DESTINO,
    DestinoCab.DTPREVENT AS DTPREVENT_DESTINO,
    TGFDTP.DTPREV AS DTPREVENT_DESTINO_ITEM,
    CASE
        WHEN DestinoCab.PENDENTE = 'S' THEN TO_CHAR(TRUNC(SYSDATE - DestinoCab.DTNEG))
        WHEN DestinoCab.PENDENTE = 'N' THEN 'Entregue'
        ELSE NULL
    END AS DIAS_EM_ABERTO_NOTA_DESTINO,
    TGFVAR_2.NUNOTA AS PROXIMA_NOTA_DESTINO,
    TGFCAB_1.NUMNOTA AS NUMNOTA_DESTINO,
    DestinoCab.CODPARC AS CODPARC_DESTINO,
    TGFPAR.NOMEPARC AS NOMEPARC_DESTINO,
    DestinoCab.DTPREVENT AS DTPREVENT_DESTINO,
    TGFDTP.DTPREV AS DTPREVENT_DESTINO_ITEM
FROM TGFCAB
INNER JOIN TGFITE ON TGFITE.NUNOTA = TGFCAB.NUNOTA
INNER JOIN TGFPRO ON TGFPRO.CODPROD = TGFITE.CODPROD
INNER JOIN TGFTOP ON (TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER)
LEFT JOIN TGFDTP ON (TGFITE.NUNOTA = TGFDTP.NUNOTA AND TGFDTP.SEQUENCIA = TGFITE.SEQUENCIA)
LEFT JOIN TGFEST ON (TGFEST.CODPROD = TGFITE.CODPROD AND TGFEST.CODEMP = TGFCAB.CODEMP)
LEFT JOIN TGFVAR ON (TGFVAR.NUNOTAORIG = TGFCAB.NUNOTA AND TGFVAR.SEQUENCIAORIG = TGFITE.SEQUENCIA)
LEFT JOIN TGFCAB DestinoCab ON TGFVAR.NUNOTA = DestinoCab.NUNOTA
LEFT JOIN TGFITE DestinoItem ON (TGFVAR.NUNOTA = DestinoItem.NUNOTA AND TGFVAR.SEQUENCIA = DestinoItem.SEQUENCIA)
LEFT JOIN TGFPAR ON DestinoCab.CODPARC = TGFPAR.CODPARC
LEFT JOIN TGFVAR TGFVAR_2 ON (TGFVAR.NUNOTA = TGFVAR_2.NUNOTAORIG AND TGFVAR.SEQUENCIA = TGFVAR_2.SEQUENCIAORIG)
LEFT JOIN TGFCAB TGFCAB_1 ON TGFVAR_2.NUNOTA = TGFCAB_1.NUNOTA
WHERE TGFCAB.CODTIPOPER = '1964'
ORDER BY TGFCAB.DTNEG, TGFCAB.NUMNOTA, TGFCAB.NUNOTA